# Generated by Django 3.2.3 on 2021-07-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
